# config/packages/rate_limiter.yaml
framework:
    rate_limiter:
        anonymous_api:
            # use 'sliding_window' if you prefer that policy
            policy: 'fixed_window'
            limit: 1
            interval: '1 minutes'
        authenticated_api:
            policy: 'token_bucket'
            limit: 1
            # "amount" toutes les "limit"
            rate: { interval: '1 minutes', amount: 1 }